var myLanguages = ['German', 'Urdu', 'Spanish', 'Arabic', 'Turkish'];
var autoGeneratedArr = [];
for (var _i = 0, myLanguages_1 = myLanguages; _i < myLanguages_1.length; _i++) {
    var lang = myLanguages_1[_i];
    autoGeneratedArr.push(lang);
}
console.log('Auto Generated Array: ', autoGeneratedArr);
