let myLanguages : string[] = ['German', 'Urdu', 'Spanish', 'Arabic', 'Turkish'];

let autoGeneratedArr : string[] = [];

for (let lang of myLanguages) {
    autoGeneratedArr.push(lang);
}

// console.log('Auto Generated Array: ', autoGeneratedArr);