var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
car = 'hyundai';
console.log("Is car == 'subaru'? I predict False.");
console.log(car == 'subaru');
console.log("Is car != 'subaru'? I predict True.");
console.log(car != 'subaru');
var _token = 34;
console.log("Is _token == 5? I predict False.");
console.log(_token == 5);
console.log("Is _token > 2? I predict True.");
console.log(_token > 2);
console.log("Is _token <= 33? I predict False.");
console.log(_token <= 33);
console.log("Is _token <= 36? I predict True.");
console.log(_token <= 36);
console.log("Is _token < 40? I predict True.");
console.log(_token < 40);
console.log("Is _token > 36? I predict False.");
console.log(_token > 36);
